apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-production
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
    notifications.argoproj.io/subscribe.on-deployed.keptn: ""
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: production
    keptnService: podtatohead
    keptnProject: demo
spec:
  destination:
    namespace: "podtatohead-production"
    server: https://34.134.64.60
  project: thschue
  source:
    path: chart 
    repoURL: https://github.com/thschue/argo-demo-install
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
