apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-production
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: production
    keptnService: podtatohead
    keptnProject: demo
spec:
  destination:
    namespace: "podtatohead-production"
    server: https://35.238.94.158
  project: thschue
  source:
    path: chart 
    repoURL: https://github.com/thschue/argo-demo-install
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
