apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
    notifications.argoproj.io/subscribe.on-deployed.keptn: ""
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: dev
    keptnService: podtatohead
    keptnProject: demo
spec:
  destination:
    namespace: "podtatohead-dev"
    server: https://34.134.64.60
  project: thschue
  source:
    chart: podtato-head
    repoURL: https://thschue.github.io/podtato-head
    targetRevision: 0.1.1-dev-main.202205060721 
    helm:
      parameters:
      - name: keptn.project
        value: "podtatohead"
      - name: keptn.stage
        name: "dev"
      - name: hat.partNumber
        value: "03"
      - name: leftArm.partNumber
        value: "04"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
