apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
    notifications.argoproj.io/subscribe.on-deployed.keptn: ""
    link.argocd.argoproj.io/external-link: https://demo.research.dev.dynatracelabs.com/bridge/project/argo-demo/sequence
    externalURI: http://35.188.108.82
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: dev
    keptnService: podtatohead
    keptnProject: argo-demo
spec:
  destination:
    namespace: "podtatohead-dev"
    server: https://35.238.94.158
  project: thschue
  source:
    chart: podtato-head
    repoURL: https://thschue.github.io/podtato-head
    targetRevision: 0.2.0
    helm:
      parameters:
      - name: keptn.project
        value: "podtatohead"
      - name: keptn.stage
        value: "dev"
      - name: hat.partNumber
        value: "02"
      - name: leftArm.partNumber
        value: "03"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
