apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-left-leg
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync-status.keptn: ""
    notifications.argoproj.io/subscribe.on-deployed.keptn: ""
    externalURI: http://35.239.155.8
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    stage: dev
    keptnService: podtatohead-aoa-left-leg
    keptnProject: argo-appofapps
spec:
  destination:
    namespace: "podtatohead-aoa-dev"
    server: https://34.134.64.60
  project: thschue
  source:
    chart: podtato-left-leg
    repoURL: https://thschue.github.io/podtato-head
    targetRevision: 0.2.0
    helm:
      parameters:
      - name: keptn.project
        value: "podtatohead-aoa"
      - name: keptn.stage
        value: "dev"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
