apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: system
  source:
    chart: ingress-nginx 
    repoURL: https://kubernetes.github.io/ingress-nginx 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
